### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by robwatts365** [timoleo23/Teams-PhoneNumbersManager#1]
@timoleo23 it would be awesome to talk about this one! I have some ideas and a similar project running. Let's collaborate. Get in touch :)

**Comment by timoleo23** [comment]
Sure - Let's get in touch - We plan to release this project at some point this month.

**Comment by timoleo23** [comment]
Please submit contribution and report issues to the new location
https://github.com/OfficeDev/Teams-Phone-System-admin-app.git
