### ISSUE TITLE
Direct Routing

### ISSUE THREAD

**Issue by LycheeYum** [timoleo23/Teams-PhoneNumbersManager#2]
It's stated that direct routing it out of scope is that because of the commands used in Azure Functions?

Would it be possible to modify those functions to the ones needed for direct routing or this a limitation of azure functions themselves?

Thank you

**Comment by timoleo23** [comment]
Hi, this is totally doable but requires to use other PowerShell cmdlets. The architecture overall is the same.

**Comment by timoleo23** [comment]
closing issue
