### ISSUE TITLE
Multiple Azure Subscriptions: Deployment script not providing the option to select a different subscription

### ISSUE THREAD

**Issue by JohanVeldhuis** [timoleo23/Teams-PhoneNumbersManager#5]
When running the deployment script in an environment with multiple subscriptions it picks just one of them. It should prompt the user to select the subscription in case multiple subscriptions are detected and allow the user to select the correct subscription

**Comment by timoleo23** [comment]
Please submit contribution and report issues to the new location
https://github.com/OfficeDev/Teams-Phone-System-admin-app.git
